### ISSUE TITLE
Across data not surfacing on dashboard

### ISSUE THREAD

**Issue by cc7768** [DefiLlama/bridges-server#13]
I submitted a PR (https://github.com/DefiLlama/bridges-server/pull/12) to update the Across adapter. The adapter worked locally but new Across data does not seem to be flowing into the dashboard.

Is there somewhere that I can see what's happening so that I can help debug/fix the adapter?

**Comment by cc7768** [comment]
@realdealshaman - Any chance we can get some insight into this so we can help iron out whatever went wrong?

We'd love to have the new data live on the bridge dashboard.

**Comment by 0xngmi** [comment]
This was fixed some weeks ago, could you confirm that the current data for across is correct?

Btw in the future it's better to contact us through discord because we don't pay much attention to issues (since almost nobody contacts us this way)

**Comment by cc7768** [comment]
Confirmed.
